"""Generate a ready-to-open Colab notebook for ultra-milk training.

Priority order:
1. Google Drive: /content/drive/MyDrive/ultra-milk-yolo-ready/
2. Roboflow direct download (requires URL + key)
3. Manual zip upload via files.upload()
"""
import json
from pathlib import Path

out = Path(__file__).parent / "ultra-milk-training.ipynb"

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 0. Setup — Sumber Dataset\n",
            "\n",
            "Notebook ini otomatis mencari dataset dengan prioritas:\n",
            "1. Google Drive: `/content/drive/MyDrive/ultra-milk-yolo-ready/`\n",
            "2. Download langsung dari Roboflow\n",
            "3. Upload zip manual via dialog\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# Langkah 1: Mount Drive dan deteksi sumber dataset\n",
            "# ============================================\n",
            "from google.colab import drive\n",
            "from google.colab import files\n",
            "from pathlib import Path\n",
            "import zipfile\n",
            "import os\n",
            "\n",
            "# Mount Drive (akan muncul link autentikasi)\n",
            "drive.mount('/content/drive')\n",
            "\n",
            "# Konfigurasi — ubah sesuai kebutuhan\n",
            "ROBOFLOW_URL = \"https://app.roboflow.com/ds/4x8WPK61Gb?key=Cs5FhO8IwZ\"\n",
            "DRIVE_PATH = Path('/content/drive/MyDrive/ultra-milk-yolo-ready')\n",
            "CONTENT_PATH = Path('/content/ultra-milk-yolo-ready')\n",
            "DRIVE_ZIP = Path('/content/drive/MyDrive/ultra-milk-yolo-ready.zip')\n",
            "\n",
            "def ensure_dataset(base: Path) -> Path:\n",
            "    if base.exists() and (base / 'data.yaml').exists():\n",
            "        return base\n",
            "    return None\n",
            "\n",
            "def rename_classes(data_yaml_path: Path) -> None:\n",
            "    text = data_yaml_path.read_text(encoding='utf-8')\n",
            "    old = \"names: ['um_normal', 'um_rusak']\"\n",
            "    new = \"names: ['passed', 'damaged']\"\n",
            "    if old in text:\n",
            "        text = text.replace(old, new)\n",
            "        data_yaml_path.write_text(text, encoding='utf-8')\n",
            "        print('Class names renamed: um_normal -> passed, um_rusak -> damaged')\n",
            "    else:\n",
            "        print('Class names already renamed or different format')\n",
            "\n",
            "# Prioritas 1: dataset sudah ada di Drive\n",
            "if ensure_dataset(DRIVE_PATH):\n",
            "    base = DRIVE_PATH\n",
            "    print(f'Dataset ditemukan di Google Drive: {base}')\n",
            "    # Rename classes untuk kompatibilitas SortVision\n",
            "    rename_classes(base / 'data.yaml')\n",
            "# Prioritas 2: download dari Roboflow\n",
            "elif ROBOFLOW_URL:\n",
            "    print('Mendownload dataset dari Roboflow...')\n",
            "    zip_path = Path('/content/roboflow.zip')\n",
            "    os.system(f'curl -L \"{ROBOFLOW_URL}\" -o {zip_path}')\n",
            "    \n",
            "    if zip_path.exists():\n",
            "        print(f'Mengekstrak {zip_path}...')\n",
            "        with zipfile.ZipFile(zip_path, 'r') as z:\n",
            "            z.extractall('/content/')\n",
            "        zip_path.unlink()\n",
            "        \n",
            "        # Cari folder yang berisi data.yaml\n",
            "        extracted = CONTENT_PATH\n",
            "        base = ensure_dataset(extracted)\n",
            "        if base is None:\n",
            "            # Kadang Roboflow extract ke subfolder\n",
            "            for subdir in CONTENT_PATH.iterdir():\n",
            "                if subdir.is_dir() and ensure_dataset(subdir):\n",
            "                    base = subdir\n",
            "                    break\n",
            "        \n",
            "        if base is not None:\n",
            "            rename_classes(base / 'data.yaml')\n",
            "            print(f'Dataset siap di: {base}')\n",
            "        else:\n",
            "            raise FileNotFoundError('data.yaml tidak ditemukan setelah ekstrak Roboflow.')\n",
            "    else:\n",
            "        raise FileNotFoundError('Gagal download dari Roboflow.')\n",
            "# Prioritas 3: zip ada di Drive, ekstrak\n",
            "elif DRIVE_ZIP.exists():\n",
            "    print(f'Mengekstrak zip dari Drive: {DRIVE_ZIP}')\n",
            "    with zipfile.ZipFile(DRIVE_ZIP, 'r') as z:\n",
            "        z.extractall('/content/')\n",
            "    base = ensure_dataset(CONTENT_PATH)\n",
            "    if base is None:\n",
            "        raise FileNotFoundError(f'Zip diekstrak, tetapi data.yaml tidak ada di {CONTENT_PATH}.')\n",
            "    print(f'Dataset siap di: {base}')\n",
            "# Prioritas 4: fallback — upload manual\n",
            "else:\n",
            "    print('Dataset tidak ditemukan. Silakan upload zip manual: \\n')\n",
            "    uploaded = files.upload()\n",
            "    zip_name = next(iter(uploaded.keys()))\n",
            "    zip_path = Path('/content') / zip_name\n",
            "    with zipfile.ZipFile(zip_path, 'r') as z:\n",
            "        z.extractall('/content/')\n",
            "    base = ensure_dataset(CONTENT_PATH)\n",
            "    if base is None:\n",
            "        raise FileNotFoundError('Zip diupload, tetapi data.yaml tidak ditemukan.')\n",
            "    print(f'Dataset siap di: {base}')\n",
            "\n",
            "# Set global paths\n",
            "DATA_BASE = str(base)\n",
            "DATA_YAML = str(base / 'data.yaml')\n",
            "\n",
            "print('\\nKonfigurasi dataset:')\n",
            "print(f'  Base   : {DATA_BASE}')\n",
            "print(f'  YAML   : {DATA_YAML}')\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 1. Install Ultralytics + Cek GPU"],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "%pip install -q ultralytics\n",
            "\n",
            "import torch\n",
            "print('PyTorch version    :', torch.__version__)\n",
            "print('CUDA available     :', torch.cuda.is_available())\n",
            "if torch.cuda.is_available():\n",
            "    print('GPU                :', torch.cuda.get_device_name(0))\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 2. Train Model YOLOv8"],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from ultralytics import YOLO\n",
            "\n",
            "use_cuda = torch.cuda.is_available()\n",
            "\n",
            "print('Data yaml  :', DATA_YAML)\n",
            "print('Epochs     :', 10)\n",
            "print('Device     :', 'cuda' if use_cuda else 'cpu')\n",
            "\n",
            "model = YOLO('yolov8n.pt')\n",
            "model.train(\n",
            "    data=DATA_YAML,\n",
            "    epochs=10,\n",
            "    imgsz=640,\n",
            "    batch=16,\n",
            "    device='cuda' if use_cuda else 'cpu',\n",
            "    workers=2,\n",
            "    cache=False,\n",
            "    project='/content/runs/detect',\n",
            "    name='train',\n",
            "    exist_ok=True,\n",
            ")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 3. Download best.pt"],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from google.colab import files\n",
            "from pathlib import Path\n",
            "\n",
            "best = Path('/content/runs/detect/train/weights/best.pt')\n",
            "if not best.exists():\n",
            "    raise FileNotFoundError(f'best.pt tidak ditemukan di {best}. Pastikan training selesai.')\n",
            "\n",
            "files.download(str(best))\n",
            "print('Downloaded:', best)\n",
        ],
    },
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print(f"Wrote notebook: {out}")
